### ISSUE TITLE
Code is quite messy. Needs to be reformatted

### ISSUE THREAD

**Issue by ShayanPersonal** [UCSB-CS56-Projects/cs56-games-treasure-hunter#13]
Needs proper indenting to make code clearer. 
Some variables (like messageBox) are not used. 
Some comments need to be replaced (description of GameGui.java is wrong). 
Some of the professor's annotations need to be removed. 
Some of the imported library's are never used.

**Comment by dcoffill** [comment]
Estimated ~250 points

**Comment by danielledodd** [comment]
Completed
