### ISSUE TITLE
Game Messages and Sprite Hide Critical Game Elements

### ISSUE THREAD

**Issue by ShayanPersonal** [UCSB-CS56-Projects/cs56-games-treasure-hunter#15]
The white background around the game messages and player sprite are intrusive and hide critical game elements like the bushes, which may hide treasure. Transparency needs to be added and the message box should be ran on a separate thread and disappear after some time.

**Comment by dcoffill** [comment]
Estimated ~200

**Comment by danielledodd** [comment]
Completed

**Comment by athielk** [comment]
F16 CLOSED: Completed
