### ISSUE TITLE
Deprecated Code Needs To Be Replaced

### ISSUE THREAD

**Issue by ShayanPersonal** [UCSB-CS56-Projects/cs56-games-treasure-hunter#17]
Deprecated code (getKeyStroke(char, boolean)) from the Swing library is used to get keyboard input. This should be replaced with something modern.

**Comment by dcoffill** [comment]
Estimated ~50 points

**Comment by danielledodd** [comment]
Completed

**Comment by athielk** [comment]
F16 CLOSED: completed
