### ISSUE TITLE
Issue For Next Class: Add Treasure Sprites!

### ISSUE THREAD

**Issue by ShayanPersonal** [UCSB-CS56-Projects/cs56-games-treasure-hunter#19]
Walking over a bush and finding treasure opens a message box but provides no other visual feedback of encountering treasure. The bush should turn into a treasure box when the player finds treasure.

**Comment by dcoffill** [comment]
Approved
Estimated ~100

**Comment by danielledodd** [comment]
Completed

**Comment by athielk** [comment]
F16 CLOSED: Completed
