### ISSUE TITLE
Issue For Next Class: Add a "You Win" Screen After Finding All Treasure

### ISSUE THREAD

**Issue by ShayanPersonal** [UCSB-CS56-Projects/cs56-games-treasure-hunter#20]
The game currently has no end. You can continue to play even after finding all three treasures.

After finding all the treasure, the program should indicate to the player that they've completed the game. For example, upon encountering the 3rd treasure, the game should pause and display a message box telling the player that they've won, and ask if they'd like to restart.

**Comment by dcoffill** [comment]
Approved
Estimated ~250

**Comment by athielk** [comment]
F16 OK (250 pts)

**Comment by athielk** [comment]
Added Game Over message does not create a menu.

**Comment by lisaljy** [comment]
I will add them later on then~
