### ISSUE TITLE
Lag Time of Player Movement

### ISSUE THREAD

**Issue by danielledodd** [UCSB-CS56-Projects/cs56-games-treasure-hunter#23]
When you are moving the player, you can press different arrow keys. However, when you press the arrow keys too fast, there is a lag time between the button pressed and the actual movement because the character isn't moving fast enough. Can be fixed by either registering the user's pressed arrow keys only when the character has stopped moving or speeding up the character's movements.

**Comment by danielledodd** [comment]
duplicate of issue #9

**Comment by athielk** [comment]
F16 CLOSED: Duplicate issue
