### ISSUE TITLE
Code for treasure sprite image

### ISSUE THREAD

**Issue by danielledodd** [UCSB-CS56-Projects/cs56-games-treasure-hunter#28]
The implementation code in GameComponent.java to make a treasure appear after finding it could be improved. Right now, its not considered to be "good code". The use of String variables can be misleading because the String is only used to activate the treasure image. For example,

```
if(!t.equals(""))
       g.drawImage(treasure.getCurrentImage(), treasure.getXPos(), treasure.getYPos(),null);

```

The t variable is currently an instance String variable. It really has no connection to the actual image. To fix, you could put the drawImage in a function or find another type of condition to have the treasure image pop up. 

Suggested points: ~75

**Comment by vincenicoara** [comment]
W16 OK

**Comment by athielk** [comment]
F16 OK (75 pts)
Perhaps look to make the equivalent of t  an attribute of a new class for treasure look to issue #30.

**Comment by lisaljy** [comment]
we finish this issue~ This issue should be closed~ @athielk
