### ISSUE TITLE
 Allow for different character sprites

### ISSUE THREAD

**Issue by danielledodd** [ucsb-cs56-projects/cs56-games-treasure-hunter#29]
Currently there is only one character sprite to play the game with, the caveman. The user should have the option to change the character sprite image.

Suggested points: ~150

**Comment by vincenicoara** [comment]
W16 OK

**Comment by athielk** [comment]
F16 OK (150 pts)

**Comment by sean-shelton** [comment]
F17 OK (150 pts)

**Comment by CDLlo** [comment]
W18 OK 150 points

**Comment by john-lau** [comment]
closed with pull request #71
