### ISSUE TITLE
Update the README.md

### ISSUE THREAD

**Issue by lisaljy** [ucsb-cs56-projects/cs56-games-treasure-hunter#46]
The picture of the game in the readme.md is a little bit out of date. Please update them with the new picture.

~20 point

**Comment by athielk** [comment]
F16 OK (20pts)

**Comment by sean-shelton** [comment]
F17 OK (20 pts)

**Comment by CDLlo** [comment]
W18 OK 20 points. At this points there is no picture whatsoever, so the addition of one would be a good start.

**Comment by john-lau** [comment]
closed with pull request #71
