### ISSUE TITLE
Create an interface

### ISSUE THREAD

**Issue by lisaljy** [ucsb-cs56-projects/cs56-games-treasure-hunter#47]
The interface or abstract class that Player.java and Treasure.java ( and any other new classes created) could  both implement. something like a gameObject 

~200 point

**Comment by athielk** [comment]
F16 OK (200pts)

**Comment by sean-shelton** [comment]
F17 OK (150 pts)

**Comment by CDLlo** [comment]
W18 OK 150 points

**Comment by john-lau** [comment]
Closed with pull request #71
