### ISSUE TITLE
Randomly generate  the tile on the map

### ISSUE THREAD

**Issue by lisaljy** [ucsb-cs56-projects/cs56-games-treasure-hunter#48]
Make Tile classes; bush, grass, stone.  Look at treasure for help and inspiration.    
(watch out: make sure treasures and stone do not overlap or you can't win)
~300

**Comment by athielk** [comment]
F16 OK (300pts)

**Comment by sangminoh715** [comment]
Estimate: ~50 (if they don't make sure that all treasures are reachable)
Estimate: ~150 (if they do check that all treasures are reachable)

**Comment by sean-shelton** [comment]
Following the point estimate given above, but for now:

F17 OK (50 points)

**Comment by CDLlo** [comment]
Same as Issue #44. W18 OK 150 points

**Comment by john-lau** [comment]
Closed with pull request #71
