### ISSUE TITLE
When the game finishes, should take player back to Main Menu

### ISSUE THREAD

**Issue by sean-shelton** [ucsb-cs56-projects/cs56-games-treasure-hunter#52]
Do issue #51 before going here!

Right now, when the game finishes, the player is left inside of the game with no way to exit except for closing the window. If the main menu has been created, it should take the player back to the main menu (maybe with an end game menu that has options like "Main Menu", "Restart", "Exit", etc.)

Estimated 100 points

**Comment by sean-shelton** [comment]
F17 OK (75 pts)

**Comment by CDLlo** [comment]
W18 OK 75 points

**Comment by john-lau** [comment]
closed with pull request #71
