### ISSUE TITLE
Refactoring the Pause Menu Code

### ISSUE THREAD

**Issue by sangminoh715** [UCSB-CS56-Projects/cs56-games-treasure-hunter#63]
As of right now, all of the code that creates and handles the game pausing is in one class. The code should be separated such that all visual elements (panels, buttons, etc.) are created in one class and all of the logic (game stopping while pause menu is showing, listening for button press to escape from the pause menu) should be located in a separate class.

**Comment by sean-shelton** [comment]
F17 OK (100 pts)
