### ISSUE TITLE
Options/Controls in the Main Menu

### ISSUE THREAD

**Issue by sangminoh715** [ucsb-cs56-projects/cs56-games-treasure-hunter#64]
Right now, all of the game's parameters (i.e. timer duration, number of treasures) are hard-coded. There should be an options menu within the main menu that allows the player to set the timer and the number of treasures in the map. However, these parameters should still have a default value so that the game can be run without the player having to go into the options menu before starting the game each time.

In addition, there can be a part of the menu that shows the controls of the game so any player (who doesn't have the README instructions) can learn how to play the game.

**Comment by Nawakhtha** [comment]
Estimate (150pts)

**Comment by sean-shelton** [comment]
F17 OK (150 pts)

**Comment by sean-shelton** [comment]
Points should be awarded if going through options/controls and changing settings does in fact change elements of the game itself

**Comment by CDLlo** [comment]
W18 OK 150 points

**Comment by john-lau** [comment]
closed with pull request #70
