### ISSUE TITLE
Add a two player gamemode

### ISSUE THREAD

**Issue by mastergberry** [ucsb-cs56-projects/cs56-games-treasure-hunter#8]
Create a split pane gui where you can have two players (one controls with AWSD and the other with arrow keys).  Whoever can find the treasure first wins the round.  The maps should be different so that they cannot screen peek on each other.  The same number of treasures should be found in each pane.  Should display a nice message who wins the round when one player finds all of the treasures in his/her pane.

Estimated 200 points

**Comment by athielk** [comment]
F16 OK (200 pts)

**Comment by sean-shelton** [comment]
F17 OK (200 pts)

**Comment by CDLlo** [comment]
W18 OK 200 points

**Comment by john-lau** [comment]
closed with pull request #70
