### ISSUE TITLE
Less sensitive input

### ISSUE THREAD

**Issue by dcoffill** [UCSB-CS56-Projects/cs56-games-treasure-hunter#9]
The current controls are very sensitive.  If you press and hold one of the arrow keys, you can't take control of the player character until the input buffer is empty, usually after the character runs into a wall.  Make the input less sensitive so that holding an arrow key for a few seconds doesn't make the game unplayable.

Estimated: ~300 points

**Comment by athielk** [comment]
F16 OK (300pts)

**Comment by sean-shelton** [comment]
F17 OK (200 pts)
